# Generated by Django 3.2.6 on 2021-08-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_project_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_screenshot',
            field=models.ImageField(blank=True, upload_to='project_images'),
        ),
    ]
