# Generated by Django 3.2.6 on 2021-08-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_project_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_link',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gitlab_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
