# Generated by Django 3.2.6 on 2021-09-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100, null=True)),
                ('headshot', models.ImageField(blank=True, upload_to='home_images')),
                ('bio', models.TextField(max_length=1000)),
            ],
        ),
    ]
